# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTableWidget, QApplication, QMainWindow, QTableWidgetItem, QFileDialog

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1275, 866)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox_4)
        self.formLayout.setObjectName("formLayout")
        self.label_d1 = QtWidgets.QLabel(self.groupBox_4)
        self.label_d1.setObjectName("label_d1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_d1)
        self.label_d1_data = QtWidgets.QLabel(self.groupBox_4)
        self.label_d1_data.setObjectName("label_d1_data")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_d1_data)
        self.label_d2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_d2.setObjectName("label_d2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_d2)
        self.label_d2_data = QtWidgets.QLabel(self.groupBox_4)
        self.label_d2_data.setObjectName("label_d2_data")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_d2_data)
        self.label_d3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_d3.setObjectName("label_d3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_d3)
        self.label_d3_data = QtWidgets.QLabel(self.groupBox_4)
        self.label_d3_data.setObjectName("label_d3_data")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_d3_data)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_save_vsm = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_save_vsm.setObjectName("pushButton_save_vsm")
        self.horizontalLayout_3.addWidget(self.pushButton_save_vsm)
        self.pushButton_up_vsm = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_up_vsm.setObjectName("pushButton_up_vsm")
        self.horizontalLayout_3.addWidget(self.pushButton_up_vsm)
        self.pushButton_save_bf = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_save_bf.setObjectName("pushButton_save_bf")
        self.horizontalLayout_3.addWidget(self.pushButton_save_bf)
        self.pushButton_up_bf = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_up_bf.setObjectName("pushButton_up_bf")
        self.horizontalLayout_3.addWidget(self.pushButton_up_bf)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableWidget_dropzone = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableWidget_dropzone.setMinimumSize(QtCore.QSize(602, 295))
        self.tableWidget_dropzone.setMaximumSize(QtCore.QSize(602, 295))
        self.tableWidget_dropzone.setObjectName("tableWidget_dropzone")
        self.tableWidget_dropzone.setColumnCount(0)
        self.tableWidget_dropzone.setRowCount(0)
        self.verticalLayout_5.addWidget(self.tableWidget_dropzone)
        self.textEdit_comment = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_comment.setMinimumSize(QtCore.QSize(602, 0))
        self.textEdit_comment.setMaximumSize(QtCore.QSize(602, 16777215))
        self.textEdit_comment.setObjectName("textEdit_comment")
        self.verticalLayout_5.addWidget(self.textEdit_comment)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setMinimumSize(QtCore.QSize(400, 0))
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.tableWidget_XLS = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget_XLS.setObjectName("tableWidget_XLS")
        self.tableWidget_XLS.setColumnCount(0)
        self.tableWidget_XLS.setRowCount(0)
        self.verticalLayout_4.addWidget(self.tableWidget_XLS)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.textEdit_comment.raise_()
        self.groupBox_2.raise_()
        self.tableWidget_XLS.raise_()
        self.label.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1275, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.menuFile.addAction(self.actionPreferences)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Array upload"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Data"))
        self.label_d1.setText(_translate("MainWindow", "Desc"))
        self.label_d1_data.setText(_translate("MainWindow", "Data"))
        self.label_d2.setText(_translate("MainWindow", "Desc"))
        self.label_d2_data.setText(_translate("MainWindow", "Data"))
        self.label_d3.setText(_translate("MainWindow", "Desc"))
        self.label_d3_data.setText(_translate("MainWindow", "Data"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Operations"))
        self.pushButton_save_vsm.setText(_translate("MainWindow", "Save Variant Studio Manifest"))
        self.pushButton_up_vsm.setText(_translate("MainWindow", "Upload to Variant Studio"))
        self.pushButton_save_bf.setText(_translate("MainWindow", "Save Bluefuse Multi Manifest"))
        self.pushButton_up_bf.setText(_translate("MainWindow", "Upload to Bluefuse Multi"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Dropzone and Comments"))
        self.groupBox.setTitle(_translate("MainWindow", "Dragzone"))
        self.label.setText(_translate("MainWindow", "Open samples Excel sheet"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

