# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1265, 756)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMaximumSize(QtCore.QSize(622, 16777215))
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_save_vsm = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_save_vsm.setObjectName("pushButton_save_vsm")
        self.horizontalLayout_3.addWidget(self.pushButton_save_vsm)
        self.pushButton_up_vsm = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_up_vsm.setObjectName("pushButton_up_vsm")
        self.horizontalLayout_3.addWidget(self.pushButton_up_vsm)
        self.pushButton_save_bf = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_save_bf.setObjectName("pushButton_save_bf")
        self.horizontalLayout_3.addWidget(self.pushButton_save_bf)
        self.pushButton_up_bf = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_up_bf.setObjectName("pushButton_up_bf")
        self.horizontalLayout_3.addWidget(self.pushButton_up_bf)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setMaximumSize(QtCore.QSize(622, 16777215))
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_d1 = QtWidgets.QLabel(self.groupBox_4)
        self.label_d1.setObjectName("label_d1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_d1)
        self.label_d3_data = QtWidgets.QLabel(self.groupBox_4)
        self.label_d3_data.setObjectName("label_d3_data")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_d3_data)
        self.label_d2_data = QtWidgets.QLabel(self.groupBox_4)
        self.label_d2_data.setObjectName("label_d2_data")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_d2_data)
        self.label_d1_data = QtWidgets.QLabel(self.groupBox_4)
        self.label_d1_data.setObjectName("label_d1_data")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_d1_data)
        self.label_d3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_d3.setObjectName("label_d3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_d3)
        self.label_d2 = QtWidgets.QLabel(self.groupBox_4)
        self.label_d2.setObjectName("label_d2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_d2)
        self.horizontalLayout_8.addLayout(self.formLayout)
        self.formLayout_6 = QtWidgets.QFormLayout()
        self.formLayout_6.setObjectName("formLayout_6")
        self.label_6 = QtWidgets.QLabel(self.groupBox_4)
        self.label_6.setObjectName("label_6")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.groupBox_4)
        self.label_7.setObjectName("label_7")
        self.formLayout_6.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.groupBox_4)
        self.label_8.setObjectName("label_8")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setObjectName("label_9")
        self.formLayout_6.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_9)
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setObjectName("label_10")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.label_11 = QtWidgets.QLabel(self.groupBox_4)
        self.label_11.setObjectName("label_11")
        self.formLayout_6.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_11)
        self.horizontalLayout_8.addLayout(self.formLayout_6)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setMaximumSize(QtCore.QSize(622, 16777215))
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setObjectName("label_3")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBox_project_type = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_project_type.setMinimumSize(QtCore.QSize(220, 0))
        self.comboBox_project_type.setMaximumSize(QtCore.QSize(220, 16777215))
        self.comboBox_project_type.setObjectName("comboBox_project_type")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_project_type)
        self.label_4 = QtWidgets.QLabel(self.groupBox_5)
        self.label_4.setObjectName("label_4")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit_project_name = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_project_name.setMinimumSize(QtCore.QSize(220, 0))
        self.lineEdit_project_name.setMaximumSize(QtCore.QSize(220, 16777215))
        self.lineEdit_project_name.setObjectName("lineEdit_project_name")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_project_name)
        self.horizontalLayout_4.addLayout(self.formLayout_4)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox_5)
        self.label_2.setObjectName("label_2")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboBox_investigator = QtWidgets.QComboBox(self.groupBox_5)
        self.comboBox_investigator.setMinimumSize(QtCore.QSize(211, 0))
        self.comboBox_investigator.setMaximumSize(QtCore.QSize(211, 16777215))
        self.comboBox_investigator.setObjectName("comboBox_investigator")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_investigator)
        self.dateEdit = QtWidgets.QDateEdit(self.groupBox_5)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.dateEdit)
        self.label_5 = QtWidgets.QLabel(self.groupBox_5)
        self.label_5.setObjectName("label_5")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout_4.addLayout(self.formLayout_3)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setMaximumSize(QtCore.QSize(622, 16777215))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableWidget_dropzone = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableWidget_dropzone.setMinimumSize(QtCore.QSize(602, 295))
        self.tableWidget_dropzone.setMaximumSize(QtCore.QSize(602, 295))
        self.tableWidget_dropzone.setObjectName("tableWidget_dropzone")
        self.tableWidget_dropzone.setColumnCount(0)
        self.tableWidget_dropzone.setRowCount(0)
        self.verticalLayout_5.addWidget(self.tableWidget_dropzone)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setMaximumSize(QtCore.QSize(622, 16777215))
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.textEdit_comment = QtWidgets.QTextEdit(self.groupBox_6)
        self.textEdit_comment.setMinimumSize(QtCore.QSize(602, 0))
        self.textEdit_comment.setMaximumSize(QtCore.QSize(602, 16777215))
        self.textEdit_comment.setObjectName("textEdit_comment")
        self.horizontalLayout_2.addWidget(self.textEdit_comment)
        self.verticalLayout_2.addWidget(self.groupBox_6)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.load_samples_comboBox = QtWidgets.QComboBox(self.groupBox)
        self.load_samples_comboBox.setMinimumSize(QtCore.QSize(150, 0))
        self.load_samples_comboBox.setMaximumSize(QtCore.QSize(10000, 16777215))
        self.load_samples_comboBox.setObjectName("load_samples_comboBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.load_samples_comboBox)
        self.verticalLayout_4.addLayout(self.formLayout_2)
        self.tableWidget_XLS = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget_XLS.setObjectName("tableWidget_XLS")
        self.tableWidget_XLS.setColumnCount(0)
        self.tableWidget_XLS.setRowCount(0)
        self.verticalLayout_4.addWidget(self.tableWidget_XLS)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1265, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionPreferences)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Array upload"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Actions"))
        self.pushButton_save_vsm.setText(_translate("MainWindow", "Save VS SampleSheet"))
        self.pushButton_up_vsm.setText(_translate("MainWindow", "Import to Variant Studio"))
        self.pushButton_save_bf.setText(_translate("MainWindow", "Save BFM SampleSheet"))
        self.pushButton_up_bf.setText(_translate("MainWindow", "Import to Bluefuse Multi"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Data"))
        self.label_d1.setText(_translate("MainWindow", "Barcode path"))
        self.label_d3_data.setText(_translate("MainWindow", "Data"))
        self.label_d2_data.setText(_translate("MainWindow", "Data"))
        self.label_d1_data.setText(_translate("MainWindow", "Data"))
        self.label_d3.setText(_translate("MainWindow", "Array data path"))
        self.label_d2.setText(_translate("MainWindow", "Manifests path"))
        self.label_6.setText(_translate("MainWindow", "Sample sheets path"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "Project name"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "Investigator"))
        self.label_11.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Experiment details"))
        self.label_3.setText(_translate("MainWindow", "Project type:"))
        self.label_4.setText(_translate("MainWindow", "Project name:"))
        self.label_2.setText(_translate("MainWindow", "Investigator:"))
        self.label_5.setText(_translate("MainWindow", "Experiment date:"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Array layout details dropzone"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Comments"))
        self.groupBox.setTitle(_translate("MainWindow", "Dragzone"))
        self.label.setText(_translate("MainWindow", "Open samples Excel sheet"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

