# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pref.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(482, 389)
        self.formLayout = QtWidgets.QFormLayout(Form)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEdit_institute = QtWidgets.QLineEdit(Form)
        self.lineEdit_institute.setObjectName("lineEdit_institute")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_institute)
        self.lbl_1 = QtWidgets.QLabel(Form)
        self.lbl_1.setObjectName("lbl_1")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_cluster_file = QtWidgets.QLineEdit(Form)
        self.lineEdit_cluster_file.setObjectName("lineEdit_cluster_file")
        self.horizontalLayout.addWidget(self.lineEdit_cluster_file)
        self.toolButton_cluster_file = QtWidgets.QToolButton(Form)
        self.toolButton_cluster_file.setObjectName("toolButton_cluster_file")
        self.horizontalLayout.addWidget(self.toolButton_cluster_file)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit_array_data_folder = QtWidgets.QLineEdit(Form)
        self.lineEdit_array_data_folder.setObjectName("lineEdit_array_data_folder")
        self.horizontalLayout_3.addWidget(self.lineEdit_array_data_folder)
        self.toolButton_array_data_folder = QtWidgets.QToolButton(Form)
        self.toolButton_array_data_folder.setObjectName("toolButton_array_data_folder")
        self.horizontalLayout_3.addWidget(self.toolButton_array_data_folder)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_3)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_sample_excel_files_folder = QtWidgets.QLineEdit(Form)
        self.lineEdit_sample_excel_files_folder.setObjectName("lineEdit_sample_excel_files_folder")
        self.horizontalLayout_4.addWidget(self.lineEdit_sample_excel_files_folder)
        self.toolButton_sample_excel_files_folder = QtWidgets.QToolButton(Form)
        self.toolButton_sample_excel_files_folder.setObjectName("toolButton_sample_excel_files_folder")
        self.horizontalLayout_4.addWidget(self.toolButton_sample_excel_files_folder)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_4)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lineEdit_sample_sheet_folder = QtWidgets.QLineEdit(Form)
        self.lineEdit_sample_sheet_folder.setObjectName("lineEdit_sample_sheet_folder")
        self.horizontalLayout_6.addWidget(self.lineEdit_sample_sheet_folder)
        self.toolButton_sample_sheet_folder = QtWidgets.QToolButton(Form)
        self.toolButton_sample_sheet_folder.setObjectName("toolButton_sample_sheet_folder")
        self.horizontalLayout_6.addWidget(self.toolButton_sample_sheet_folder)
        self.formLayout.setLayout(4, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_6)
        spacerItem = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(5, QtWidgets.QFormLayout.FieldRole, spacerItem)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit_add_investigator = QtWidgets.QLineEdit(Form)
        self.lineEdit_add_investigator.setObjectName("lineEdit_add_investigator")
        self.horizontalLayout_5.addWidget(self.lineEdit_add_investigator)
        self.pushButton_add_investigator = QtWidgets.QPushButton(Form)
        self.pushButton_add_investigator.setObjectName("pushButton_add_investigator")
        self.horizontalLayout_5.addWidget(self.pushButton_add_investigator)
        self.formLayout.setLayout(6, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.listWidget_investigators = QtWidgets.QListWidget(Form)
        self.listWidget_investigators.setMaximumSize(QtCore.QSize(16777215, 100))
        self.listWidget_investigators.setObjectName("listWidget_investigators")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.listWidget_investigators)
        self.pushButton_remove_investigators = QtWidgets.QPushButton(Form)
        self.pushButton_remove_investigators.setObjectName("pushButton_remove_investigators")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.pushButton_remove_investigators)
        spacerItem1 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(10, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.btn_ok = QtWidgets.QPushButton(Form)
        self.btn_ok.setObjectName("btn_ok")
        self.horizontalLayout_2.addWidget(self.btn_ok)
        self.btn_cancel = QtWidgets.QPushButton(Form)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_2.addWidget(self.btn_cancel)
        self.formLayout.setLayout(11, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Institute"))
        self.lbl_1.setText(_translate("Form", "Cluster file"))
        self.toolButton_cluster_file.setText(_translate("Form", "..."))
        self.label.setText(_translate("Form", "Array data folder"))
        self.toolButton_array_data_folder.setText(_translate("Form", "..."))
        self.label_2.setText(_translate("Form", "Sample Excel files folder"))
        self.toolButton_sample_excel_files_folder.setText(_translate("Form", "..."))
        self.label_6.setText(_translate("Form", "Sample Sheet folder"))
        self.toolButton_sample_sheet_folder.setText(_translate("Form", "..."))
        self.label_5.setText(_translate("Form", "Add Investigator"))
        self.pushButton_add_investigator.setText(_translate("Form", "Add"))
        self.label_4.setText(_translate("Form", "Investigators"))
        self.pushButton_remove_investigators.setText(_translate("Form", "Remove Selected Investigators"))
        self.btn_ok.setText(_translate("Form", "OK"))
        self.btn_cancel.setText(_translate("Form", "Cancel"))

